import { type CocktailRecipe } from "./cocktails.js";

const IBA = "IBA Classics";
const MOD = "IBA & Modern Classics";
const SEA = "Seasonal";

function recipe(
  name: string,
  ingredients: string[],
  extra: Partial<Pick<CocktailRecipe, "glassware" | "garnish" | "method" | "collection" | "season" | "notes">> = {}
): CocktailRecipe {
  return {
    name,
    ingredients,
    glassware: extra.glassware ?? "Coupe",
    garnish: extra.garnish ?? "",
    method: extra.method ?? "Shake",
    collection: extra.collection ?? MOD,
    season: extra.season ?? "All",
    notes: extra.notes ?? ""
  };
}

export const COCKTAIL_RECIPES: CocktailRecipe[] = [
  recipe("Old Fashioned", ["45 ml bourbon or rye", "1 sugar cube", "2 dashes Angostura bitters"], { collection: IBA, glassware: "Rocks", garnish: "Orange twist", method: "Stir", season: "Fall" }),
  recipe("Dry Martini", ["60 ml gin", "10 ml dry vermouth"], { collection: IBA, garnish: "Lemon twist or olive", method: "Stir" }),
  recipe("Margarita", ["50 ml tequila", "20 ml triple sec", "15 ml lime juice"], { collection: IBA, glassware: "Margarita", garnish: "Salt rim", method: "Shake", season: "Summer" }),
  recipe("Daiquiri", ["60 ml white rum", "20 ml lime juice", "2 tsp sugar"], { collection: IBA, garnish: "Lime wheel", season: "Summer" }),
  recipe("Manhattan", ["50 ml rye whiskey", "20 ml sweet vermouth", "1 dash bitters"], { collection: IBA, garnish: "Cherry", method: "Stir", season: "Winter" }),
  recipe("Negroni", ["30 ml gin", "30 ml Campari", "30 ml sweet vermouth"], { collection: IBA, glassware: "Rocks", garnish: "Orange peel", method: "Stir" }),
  recipe("Whiskey Sour", ["45 ml bourbon", "25 ml lemon juice", "20 ml sugar syrup", "egg white"], { collection: IBA, glassware: "Rocks", garnish: "Cherry" }),
  recipe("Mojito", ["45 ml white rum", "20 ml lime juice", "6 mint sprigs", "soda water", "2 tsp sugar"], { collection: IBA, glassware: "Highball", garnish: "Mint", method: "Build", season: "Summer" }),
  recipe("Moscow Mule", ["45 ml vodka", "10 ml lime juice", "ginger beer"], { collection: IBA, glassware: "Mug", garnish: "Lime", method: "Build", season: "Fall" }),
  recipe("French 75", ["30 ml gin", "15 ml lemon juice", "15 ml sugar syrup", "60 ml Champagne"], { collection: IBA, glassware: "Flute", garnish: "Lemon twist", method: "Shake and top", season: "Spring" }),
  recipe("Espresso Martini", ["50 ml vodka", "30 ml coffee liqueur", "10 ml sugar syrup", "espresso"], { collection: IBA, garnish: "Coffee beans", season: "Holiday" }),
  recipe("Mai Tai", ["30 ml amber rum", "30 ml Martinique rum", "15 ml orange curaçao", "15 ml orgeat", "30 ml lime juice"], { collection: IBA, glassware: "Rocks", garnish: "Mint", season: "Summer" }),
  recipe("Tom Collins", ["45 ml gin", "30 ml lemon juice", "15 ml sugar syrup", "60 ml soda water"], { collection: IBA, glassware: "Collins", garnish: "Lemon", method: "Shake and top", season: "Spring" }),
  recipe("Sidecar", ["50 ml cognac", "20 ml triple sec", "20 ml lemon juice"], { collection: IBA, garnish: "Orange twist" }),
  recipe("Boulevardier", ["45 ml bourbon", "30 ml Campari", "30 ml sweet vermouth"], { collection: IBA, glassware: "Rocks", garnish: "Orange twist", method: "Stir", season: "Winter" }),
  recipe("Aperol Spritz", ["90 ml prosecco", "60 ml Aperol", "30 ml soda water"], { collection: IBA, glassware: "Wine", garnish: "Orange slice", method: "Build", season: "Summer" }),
  recipe("Gimlet", ["60 ml gin", "30 ml lime cordial"], { collection: IBA, garnish: "Lime wheel", season: "Spring" }),
  recipe("Sazerac", ["50 ml cognac or rye", "10 ml absinthe", "1 sugar cube", "2 dashes Peychaud's bitters"], { collection: IBA, glassware: "Rocks", garnish: "Lemon peel", method: "Stir", season: "Winter" }),
  recipe("Pisco Sour", ["60 ml pisco", "30 ml lemon juice", "20 ml sugar syrup", "egg white"], { collection: IBA, garnish: "Bitters" }),
  recipe("Paloma", ["50 ml tequila", "5 ml lime juice", "grapefruit soda", "salt"], { collection: IBA, glassware: "Highball", garnish: "Lime", method: "Build" }),

  recipe("Alexander", ["30 ml cognac", "30 ml crème de cacao", "30 ml cream"], { collection: IBA, garnish: "Nutmeg", season: "Holiday" }),
  recipe("Americano", ["30 ml Campari", "30 ml sweet vermouth", "soda water"], { collection: IBA, glassware: "Highball", garnish: "Orange slice", method: "Build" }),
  recipe("Angel Face", ["30 ml gin", "30 ml apricot brandy", "30 ml calvados"], { collection: IBA, method: "Shake" }),
  recipe("Aviation", ["45 ml gin", "15 ml maraschino", "15 ml lemon juice", "10 ml crème de violette"], { collection: IBA, garnish: "Cherry", season: "Spring" }),
  recipe("Between the Sheets", ["30 ml rum", "30 ml cognac", "30 ml triple sec", "20 ml lemon juice"], { collection: IBA }),
  recipe("Black Russian", ["50 ml vodka", "20 ml coffee liqueur"], { collection: IBA, glassware: "Rocks", method: "Build" }),
  recipe("Bloody Mary", ["45 ml vodka", "90 ml tomato juice", "15 ml lemon juice", "Worcestershire", "hot sauce", "salt"], { collection: IBA, glassware: "Highball", garnish: "Celery", method: "Build" }),
  recipe("Bramble", ["50 ml gin", "25 ml lemon juice", "15 ml sugar syrup", "15 ml crème de mûre"], { collection: IBA, glassware: "Rocks", garnish: "Blackberry", season: "Spring" }),
  recipe("Brandy Crusta", ["50 ml brandy", "15 ml lemon juice", "7.5 ml maraschino", "7.5 ml triple sec", "1 dash bitters"], { collection: IBA, garnish: "Sugar rim and lemon" }),
  recipe("Caipirinha", ["60 ml cachaça", "1 lime", "2 tsp sugar"], { collection: IBA, glassware: "Rocks", method: "Muddle and build", season: "Summer" }),
  recipe("Canchanchara", ["60 ml rum", "15 ml lime juice", "15 ml honey"], { collection: IBA, glassware: "Rocks", method: "Build", season: "Summer" }),
  recipe("Cardinale", ["45 ml gin", "30 ml Campari", "15 ml dry vermouth"], { collection: IBA, glassware: "Rocks", garnish: "Orange peel", method: "Stir" }),
  recipe("Casino", ["40 ml gin", "10 ml maraschino", "10 ml lemon juice", "2 dashes orange bitters"], { collection: IBA, garnish: "Lemon and cherry" }),
  recipe("Champagne Cocktail", ["90 ml Champagne", "1 sugar cube", "2 dashes Angostura bitters"], { collection: IBA, glassware: "Flute", garnish: "Lemon twist", method: "Build", season: "Holiday" }),
  recipe("Clover Club", ["45 ml gin", "15 ml raspberry syrup", "15 ml lemon juice", "egg white"], { collection: IBA, garnish: "Raspberry", season: "Spring" }),
  recipe("Corpse Reviver #2", ["20 ml gin", "20 ml Cointreau", "20 ml Lillet Blanc", "20 ml lemon juice", "absinthe rinse"], { collection: IBA }),
  recipe("Cosmopolitan", ["40 ml vodka", "15 ml triple sec", "15 ml lime juice", "30 ml cranberry juice"], { collection: IBA, garnish: "Orange twist" }),
  recipe("Cuba Libre", ["50 ml rum", "120 ml cola", "10 ml lime juice"], { collection: IBA, glassware: "Highball", garnish: "Lime", method: "Build", season: "Summer" }),
  recipe("Dark 'n' Stormy", ["60 ml dark rum", "100 ml ginger beer"], { collection: IBA, glassware: "Highball", garnish: "Lime", method: "Build" }),
  recipe("Derby", ["60 ml gin", "30 ml peach bitters", "2 mint sprigs"], { collection: IBA, garnish: "Mint", method: "Stir" }),
  recipe("Dirty Martini", ["60 ml gin or vodka", "10 ml dry vermouth", "10 ml olive brine"], { collection: IBA, garnish: "Olive", method: "Stir" }),
  recipe("Don's Special Daiquiri", ["45 ml rum", "15 ml lime juice", "15 ml passion fruit syrup", "7.5 ml honey"], { garnish: "Lime", season: "Summer" }),
  recipe("Fernandito", ["50 ml fernet", "cola"], { glassware: "Highball", garnish: "Lime", method: "Build" }),
  recipe("French Connection", ["35 ml cognac", "35 ml amaretto"], { collection: IBA, glassware: "Rocks", method: "Build" }),
  recipe("Garibaldi", ["45 ml Campari", "120 ml orange juice"], { glassware: "Highball", garnish: "Orange slice", method: "Build", season: "Summer" }),
  recipe("Gin Fizz", ["45 ml gin", "30 ml lemon juice", "10 ml sugar syrup", "soda water"], { collection: IBA, glassware: "Highball", method: "Shake and top", season: "Spring" }),
  recipe("God Father", ["35 ml scotch", "35 ml amaretto"], { collection: IBA, glassware: "Rocks", method: "Build", season: "Winter" }),
  recipe("God Mother", ["35 ml vodka", "35 ml amaretto"], { collection: IBA, glassware: "Rocks", method: "Build" }),
  recipe("Golden Dream", ["20 ml triple sec", "20 ml galliano", "20 ml orange juice", "10 ml cream"], { collection: IBA, season: "Holiday" }),
  recipe("Grasshopper", ["20 ml crème de cacao", "20 ml crème de menthe", "20 ml cream"], { collection: IBA }),
  recipe("Hanky Panky", ["45 ml gin", "45 ml sweet vermouth", "7.5 ml fernet"], { collection: IBA, garnish: "Orange twist", method: "Stir" }),
  recipe("Harvey Wallbanger", ["45 ml vodka", "15 ml galliano", "90 ml orange juice"], { collection: IBA, glassware: "Highball", garnish: "Orange slice", method: "Build" }),
  recipe("Hemingway Special", ["60 ml rum", "15 ml grapefruit juice", "15 ml lime juice", "15 ml maraschino"], { collection: IBA, garnish: "Lime" }),
  recipe("Horse's Neck", ["40 ml brandy", "120 ml ginger ale", "1 dash Angostura bitters"], { collection: IBA, glassware: "Highball", garnish: "Lemon spiral", method: "Build" }),
  recipe("Illegal", ["30 ml mezcal", "15 ml Jamaican rum", "15 ml falernum", "15 ml lime juice", "10 ml maraschino", "egg white"], { collection: IBA }),
  recipe("Irish Coffee", ["50 ml Irish whiskey", "120 ml coffee", "50 ml cream", "1 tsp sugar"], { collection: IBA, glassware: "Irish Coffee", method: "Build", season: "Winter" }),
  recipe("John Collins", ["45 ml gin", "30 ml lemon juice", "15 ml sugar syrup", "60 ml soda water"], { collection: IBA, glassware: "Collins", garnish: "Lemon and cherry", method: "Shake and top" }),
  recipe("Jungle Bird", ["45 ml rum", "45 ml pineapple juice", "15 ml Campari", "15 ml lime juice", "15 ml sugar syrup"], { glassware: "Rocks", garnish: "Pineapple", season: "Summer" }),
  recipe("Kir", ["90 ml white wine", "10 ml crème de cassis"], { collection: IBA, glassware: "Wine", method: "Build" }),
  recipe("Last Word", ["22 ml gin", "22 ml green Chartreuse", "22 ml maraschino", "22 ml lime juice"], { collection: IBA }),
  recipe("Lemon Drop Martini", ["50 ml vodka", "20 ml triple sec", "15 ml lemon juice", "10 ml sugar syrup"], { garnish: "Sugar rim" }),
  recipe("Long Island Iced Tea", ["15 ml vodka", "15 ml gin", "15 ml rum", "15 ml tequila", "15 ml triple sec", "30 ml lemon juice", "20 ml sugar syrup", "cola"], { collection: IBA, glassware: "Highball", garnish: "Lemon", method: "Shake and top" }),
  recipe("Martinez", ["45 ml gin", "45 ml sweet vermouth", "7.5 ml maraschino", "2 dashes orange bitters"], { collection: IBA, garnish: "Lemon twist", method: "Stir" }),
  recipe("Mary Pickford", ["45 ml rum", "45 ml pineapple juice", "7.5 ml maraschino", "5 ml grenadine"], { collection: IBA }),
  recipe("Mimosa", ["75 ml Champagne", "75 ml orange juice"], { collection: IBA, glassware: "Flute", method: "Build", season: "Spring" }),
  recipe("Mint Julep", ["60 ml bourbon", "8 mint sprigs", "15 ml sugar syrup"], { collection: IBA, glassware: "Julep", garnish: "Mint", method: "Muddle and build", season: "Summer" }),
  recipe("Missionary's Downfall", ["30 ml rum", "15 ml peach liqueur", "15 ml lime juice", "15 ml honey", "mint", "pineapple juice"], { glassware: "Coupe", garnish: "Mint", season: "Summer" }),
  recipe("Monkey Gland", ["50 ml gin", "30 ml orange juice", "2 dashes absinthe", "2 dashes grenadine"], { collection: IBA }),
  recipe("Naked and Famous", ["22 ml mezcal", "22 ml Aperol", "22 ml yellow Chartreuse", "22 ml lime juice"], {}),
  recipe("New York Sour", ["60 ml rye whiskey", "22 ml lemon juice", "22 ml sugar syrup", "15 ml red wine"], { glassware: "Rocks", garnish: "Lemon", season: "Fall" }),
  recipe("Old Cuban", ["45 ml rum", "22 ml lime juice", "15 ml sugar syrup", "2 dashes Angostura bitters", "60 ml Champagne", "mint"], { glassware: "Coupe", garnish: "Mint" }),
  recipe("Paradise", ["35 ml gin", "20 ml apricot brandy", "15 ml orange juice"], { collection: IBA }),
  recipe("Penicillin", ["60 ml blended scotch", "22 ml lemon juice", "22 ml honey-ginger syrup", "7.5 ml peated scotch"], { glassware: "Rocks", garnish: "Ginger", season: "Winter" }),
  recipe("Piña Colada", ["50 ml rum", "30 ml coconut cream", "50 ml pineapple juice"], { collection: IBA, glassware: "Hurricane", garnish: "Pineapple", season: "Summer" }),
  recipe("Planter's Punch", ["45 ml rum", "15 ml lemon juice", "30 ml orange juice", "10 ml sugar syrup", "dash grenadine", "soda water"], { collection: IBA, glassware: "Highball", garnish: "Orange", method: "Shake and top", season: "Summer" }),
  recipe("Porto Flip", ["45 ml tawny port", "15 ml brandy", "10 ml simple syrup", "egg yolk"], { collection: IBA, garnish: "Nutmeg", season: "Winter" }),
  recipe("Ramos Fizz", ["45 ml gin", "15 ml lime juice", "15 ml lemon juice", "30 ml cream", "10 ml sugar syrup", "egg white", "3 dashes orange flower water", "soda water"], { collection: IBA, glassware: "Highball", method: "Shake hard and top" }),
  recipe("Remember the Maine", ["60 ml rye whiskey", "22 ml sweet vermouth", "7.5 ml Cherry Heering", "absinthe rinse"], { garnish: "Cherry", method: "Stir" }),
  recipe("Russian Spring Punch", ["25 ml vodka", "25 ml lemon juice", "15 ml crème de cassis", "10 ml sugar syrup", "Champagne"], { collection: IBA, glassware: "Highball", garnish: "Lemon", method: "Shake and top", season: "Spring" }),
  recipe("Rusty Nail", ["45 ml scotch", "25 ml Drambuie"], { collection: IBA, glassware: "Rocks", method: "Build", season: "Winter" }),
  recipe("Sea Breeze", ["40 ml vodka", "120 ml cranberry juice", "30 ml grapefruit juice"], { collection: IBA, glassware: "Highball", garnish: "Lime", method: "Build", season: "Summer" }),
  recipe("Sex on the Beach", ["40 ml vodka", "20 ml peach schnapps", "40 ml orange juice", "40 ml cranberry juice"], { collection: IBA, glassware: "Highball", garnish: "Orange", method: "Build" }),
  recipe("Sherry Cobbler", ["90 ml sherry", "15 ml sugar syrup", "orange slice"], { glassware: "Highball", garnish: "Berries", method: "Shake", season: "Summer" }),
  recipe("Singapore Sling", ["30 ml gin", "15 ml cherry liqueur", "7.5 ml Cointreau", "7.5 ml Bénédictine", "120 ml pineapple juice", "15 ml lime juice", "10 ml grenadine", "1 dash bitters"], { collection: IBA, glassware: "Hurricane", garnish: "Pineapple" }),
  recipe("South Side", ["60 ml gin", "22 ml lime juice", "22 ml sugar syrup", "mint"], { garnish: "Mint", season: "Spring" }),
  recipe("Spicy Fifty", ["50 ml vodka", "15 ml elderflower liqueur", "15 ml lime juice", "10 ml honey", "chili"], { collection: IBA, garnish: "Chili" }),
  recipe("Spritz Veneziano", ["90 ml prosecco", "60 ml Aperol", "30 ml soda water"], { collection: IBA, glassware: "Wine", garnish: "Orange slice", method: "Build", season: "Summer" }),
  recipe("Stinger", ["50 ml cognac", "20 ml white crème de menthe"], { collection: IBA, method: "Stir" }),
  recipe("Suffering Bastard", ["30 ml gin", "30 ml brandy", "15 ml lime juice", "2 dashes Angostura bitters", "ginger beer"], { glassware: "Highball", garnish: "Mint", method: "Shake and top" }),
  recipe("Tequila Sunrise", ["45 ml tequila", "90 ml orange juice", "15 ml grenadine"], { collection: IBA, glassware: "Highball", garnish: "Orange", method: "Build", season: "Summer" }),
  recipe("Three Dots and a Dash", ["40 ml rhum agricole", "20 ml rum", "15 ml orange curaçao", "15 ml lime juice", "15 ml honey", "7.5 ml falernum", "7.5 ml allspice dram"], { glassware: "Pilsner", garnish: "Cherries", season: "Summer" }),
  recipe("Tipperary", ["50 ml Irish whiskey", "25 ml sweet vermouth", "15 ml green Chartreuse"], { garnish: "Orange peel", method: "Stir" }),
  recipe("Tommy's Margarita", ["60 ml tequila", "30 ml lime juice", "15 ml agave syrup"], { glassware: "Rocks", garnish: "Lime" }),
  recipe("Trinidad Sour", ["40 ml Angostura bitters", "30 ml orgeat", "22 ml lemon juice", "15 ml rye whiskey"], { garnish: "Lemon" }),
  recipe("Tuxedo", ["30 ml gin", "30 ml dry vermouth", "5 ml maraschino", "absinthe rinse", "2 dashes orange bitters"], { collection: IBA, garnish: "Cherry and lemon", method: "Stir" }),
  recipe("Vampiro", ["50 ml tequila", "70 ml tomato juice", "30 ml orange juice", "10 ml lime juice", "honey", "onion salt", "chili"], { collection: IBA, glassware: "Highball", method: "Build" }),
  recipe("Vesper", ["45 ml gin", "15 ml vodka", "7.5 ml Lillet Blanc"], { collection: IBA, garnish: "Lemon twist", method: "Stir" }),
  recipe("Vieux Carré", ["30 ml rye whiskey", "30 ml cognac", "30 ml sweet vermouth", "7.5 ml Bénédictine", "2 dashes Peychaud's bitters"], { glassware: "Rocks", garnish: "Lemon", method: "Stir", season: "Winter" }),
  recipe("Vodka Martini", ["60 ml vodka", "10 ml dry vermouth"], { collection: IBA, garnish: "Lemon twist or olive", method: "Stir" }),
  recipe("White Lady", ["40 ml gin", "30 ml triple sec", "20 ml lemon juice"], { collection: IBA }),
  recipe("White Russian", ["50 ml vodka", "20 ml coffee liqueur", "30 ml cream"], { collection: IBA, glassware: "Rocks", method: "Build", season: "Holiday" }),
  recipe("Yellow Bird", ["30 ml rum", "15 ml galliano", "15 ml triple sec", "15 ml lime juice"], { collection: IBA }),
  recipe("Zombie", ["45 ml rum", "30 ml gold rum", "30 ml dark rum", "20 ml lime juice", "15 ml falernum", "15 ml grapefruit juice", "5 ml grenadine", "dash absinthe"], { glassware: "Hurricane", garnish: "Mint", season: "Summer" }),
  recipe("Paper Plane", ["22 ml bourbon", "22 ml Aperol", "22 ml Amaro Nonino", "22 ml lemon juice"], { season: "Fall" }),
  recipe("Bee's Knees", ["60 ml gin", "22 ml lemon juice", "22 ml honey"], { season: "Spring" }),
  recipe("Gold Rush", ["60 ml bourbon", "22 ml lemon juice", "22 ml honey"], { glassware: "Rocks", season: "Fall" }),
  recipe("Navy Grog", ["30 ml rum", "30 ml gold rum", "30 ml rum", "20 ml lime juice", "20 ml grapefruit juice", "20 ml honey"], { glassware: "Rocks", garnish: "Mint", season: "Summer" }),
  recipe("Painkiller", ["60 ml rum", "120 ml pineapple juice", "30 ml orange juice", "30 ml coconut cream"], { glassware: "Hurricane", garnish: "Nutmeg", season: "Summer" }),
  recipe("Saturn", ["45 ml gin", "22 ml lemon juice", "15 ml passion fruit syrup", "7.5 ml falernum", "7.5 ml orgeat"], { garnish: "Lemon", season: "Summer" }),
  recipe("Rum Old Fashioned", ["60 ml rum", "1 sugar cube", "2 dashes Angostura bitters"], { glassware: "Rocks", garnish: "Orange twist", method: "Stir" }),
  recipe("Mezcal Negroni", ["30 ml mezcal", "30 ml Campari", "30 ml sweet vermouth"], { glassware: "Rocks", garnish: "Orange peel", method: "Stir" }),
  recipe("Maple Old Fashioned", ["60 ml bourbon", "10 ml maple syrup", "2 dashes Angostura bitters"], { collection: SEA, glassware: "Rocks", garnish: "Orange twist", method: "Stir", season: "Fall" }),
  recipe("Cranberry Mule", ["45 ml vodka", "30 ml cranberry juice", "10 ml lime juice", "ginger beer"], { collection: SEA, glassware: "Mug", garnish: "Lime", method: "Build", season: "Holiday" }),
  recipe("Apple Cider Sour", ["45 ml bourbon", "45 ml apple cider", "22 ml lemon juice", "15 ml sugar syrup"], { collection: SEA, glassware: "Rocks", garnish: "Apple", season: "Fall" }),
  recipe("Hot Toddy", ["45 ml whiskey", "15 ml honey", "15 ml lemon juice", "hot water"], { collection: SEA, glassware: "Mug", garnish: "Lemon and clove", method: "Build", season: "Winter" }),
  recipe("Coquito", ["60 ml rum", "90 ml coconut milk", "30 ml cream of coconut", "15 ml sweetened condensed milk", "cinnamon"], { collection: SEA, glassware: "Rocks", garnish: "Cinnamon", method: "Shake", season: "Holiday" }),
  recipe("Kentucky Buck", ["60 ml bourbon", "22 ml lemon juice", "15 ml strawberry syrup", "2 dashes Angostura bitters", "ginger beer"], { glassware: "Highball", garnish: "Strawberry", method: "Shake and top", season: "Fall" }),
  recipe("Basil Smash", ["60 ml gin", "22 ml lemon juice", "22 ml sugar syrup", "basil"], { glassware: "Rocks", garnish: "Basil", season: "Spring" })
];
