import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { join } from "node:path";
import { test } from "node:test";
import {
  parseTastingProfile,
  stripTastingBoilerplate,
  tastingProfileHasProvenanceBoilerplate
} from "./tasting-profile.js";

const root = process.cwd();
const bottlePublicSrc = readFileSync(join(root, "client/src/BottlePublicContent.tsx"), "utf8");
const appSrc = readFileSync(join(root, "client/src/App.tsx"), "utf8");
const enrichmentPanelSrc = readFileSync(join(root, "client/src/EnrichmentPanel.tsx"), "utf8");

const GIN_EXAMPLE =
  "AI house profile (not producer copy)\nAroma: Dry juniper, citrus peel, soft coriander.\nPalate: Juniper-forward, crisp, lightly floral.\nFinish: Clean, dry, lingering juniper.";

test("A. strips AI house profile boilerplate", () => {
  const cleaned = stripTastingBoilerplate("AI house profile\nAroma: Dry juniper, citrus.");
  assert.equal(cleaned.startsWith("AI house profile"), false);
  assert.match(cleaned, /Aroma:\s*Dry juniper/);
});

test("B. strips (not producer copy)", () => {
  const cleaned = stripTastingBoilerplate("AI house profile (not producer copy)\nAroma: Pine and lemon.");
  assert.equal(/\bnot producer copy\b/i.test(cleaned), false);
  assert.match(cleaned, /Aroma:\s*Pine and lemon/);
});

test("C. strips Generated house profile — not producer copy", () => {
  const cleaned = stripTastingBoilerplate(
    "Generated house profile — not producer copy\nAroma: Orange oil.\nPalate: Soft oak."
  );
  assert.equal(/\bgenerated house profile\b/i.test(cleaned), false);
  assert.equal(/\bnot producer copy\b/i.test(cleaned), false);
  assert.match(cleaned, /Aroma:\s*Orange oil/);
});

test("D. parses Aroma correctly", () => {
  const profile = parseTastingProfile(GIN_EXAMPLE);
  assert.equal(profile.aroma, "Dry juniper, citrus peel, soft coriander.");
});

test("E. parses Palate correctly", () => {
  const profile = parseTastingProfile(GIN_EXAMPLE);
  assert.equal(profile.palate, "Juniper-forward, crisp, lightly floral.");
});

test("F. parses Finish correctly when present", () => {
  const profile = parseTastingProfile(GIN_EXAMPLE);
  assert.equal(profile.finish, "Clean, dry, lingering juniper.");
});

test("G. missing Finish is not rendered (no empty finish field)", () => {
  const profile = parseTastingProfile(
    "AI house profile (not producer copy) Aroma: Dry juniper, citrus. Palate: Juniper-forward, crisp."
  );
  assert.equal(profile.aroma, "Dry juniper, citrus.");
  assert.equal(profile.palate, "Juniper-forward, crisp.");
  assert.equal(profile.finish, undefined);
});

test("H. plain legacy tasting note remains visible as fallback", () => {
  const profile = parseTastingProfile("Bright lemon peel with a soft floral lift.");
  assert.equal(profile.fallback, "Bright lemon peel with a soft floral lift.");
  assert.equal(profile.aroma, undefined);
  assert.equal(profile.palate, undefined);
});

test("I. legitimate tasting text is not accidentally deleted", () => {
  const note =
    "Aromatic botanicals from a small producer; the finish feels generated by long barrel rest, not haste.";
  const profile = parseTastingProfile(note);
  assert.equal(profile.fallback, note);
  assert.match(profile.fallback ?? "", /small producer/);
  assert.match(profile.fallback ?? "", /generated by long barrel rest/);
});

test("J. guest display contains no AI provenance boilerplate", () => {
  assert.match(bottlePublicSrc, /Tasting Profile|TASTING PROFILE/);
  assert.doesNotMatch(bottlePublicSrc, /Generated house profile — not producer copy/);
  assert.doesNotMatch(bottlePublicSrc, /enrichment-ai-label/);
  const profile = parseTastingProfile(GIN_EXAMPLE);
  const guestBlob = ["Tasting Profile", profile.aroma, profile.palate, profile.finish]
    .filter(Boolean)
    .join("\n");
  assert.equal(tastingProfileHasProvenanceBoilerplate(guestBlob), false);
});

test("K. guest display contains no not producer copy", () => {
  assert.doesNotMatch(bottlePublicSrc, /not producer copy/i);
  assert.doesNotMatch(bottlePublicSrc, /not official producer copy/i);
  const profile = parseTastingProfile(
    "Generated house profile — not producer copy\nAroma: Citrus.\nPalate: Crisp."
  );
  const guestBlob = [profile.aroma, profile.palate, profile.finish, profile.fallback]
    .filter(Boolean)
    .join(" ");
  assert.equal(/\bnot producer copy\b/i.test(guestBlob), false);
});

test("L. Keeper/admin provenance remains available where currently supported", () => {
  assert.match(enrichmentPanelSrc, /AI house profile|Generated house profile/);
  assert.match(enrichmentPanelSrc, /not producer copy/i);
  assert.match(appSrc, /admin && ENRICHMENT_MODULES\.has\(module\.id\) \? <EnrichmentPanel/);
});

test("M. no tasting-note DB mutation helpers in guest presentation path", () => {
  assert.doesNotMatch(bottlePublicSrc, /UPDATE|prepare\(|db\.|saveTasting|mutate/);
  assert.match(bottlePublicSrc, /parseTastingProfile/);
});

test("N. no flavor-chip UI added for tasting profile", () => {
  assert.doesNotMatch(bottlePublicSrc, /flavor-chip|tasting-chip|chip-row.*tasting/i);
  assert.doesNotMatch(bottlePublicSrc, /Tags\s*:/);
});

test("O. bottle detail still renders normal metadata and Find a Drink", () => {
  assert.match(appSrc, /Find a drink with this/);
  assert.match(appSrc, /TastingProfileView/);
  assert.match(appSrc, /bottle-detail-hero/);
  assert.match(appSrc, /bottle-detail-grid/);
});

test("structured JSON house profiles parse without boilerplate", () => {
  const profile = parseTastingProfile({
    aroma: "Peat smoke",
    palate: "Honeyed malt",
    finish: "Long and drying"
  });
  assert.deepEqual(profile, {
    aroma: "Peat smoke",
    palate: "Honeyed malt",
    finish: "Long and drying"
  });
});

test("JSON string house profiles parse the same way", () => {
  const profile = parseTastingProfile(
    JSON.stringify({ aroma: "Citrus", palate: "Juniper", finish: "Dry" })
  );
  assert.equal(profile.aroma, "Citrus");
  assert.equal(profile.palate, "Juniper");
  assert.equal(profile.finish, "Dry");
});
